<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FC_Durchschnitt" Id="{5fd35583-b519-4c4c-9016-ca68ce2edbce}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FC_Durchschnitt : REAL
VAR_INPUT
	vii_Wert_1 : INT;
	vii_Wert_2 : INT;
	vii_Wert_3 : INT;
END_VAR
VAR_OUTPUT
	vqr_Durchschnitt: REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[vqr_Durchschnitt := ((vii_Wert_1 + vii_Wert_2 + vii_Wert_3) / 3 );]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>